<?php

namespace tshuvalova\PerformanceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
     public function getActiveProjects($em)
     {
         $rsm = new ResultSetMapping;
         $rsm->addEntityResult('tshuvalovaPerformanceBundle:Project', 'u');
         $rsm->addFieldResult('u', 'id', 'id');
         $rsm->addFieldResult('u', 'name', 'name');
         $rsm->addFieldResult('u', 'description', 'description');
         $rsm->addJoinedEntityResult('tshuvalovaPerformanceBundle:Task' , 'a', 'u', 'tasks');
         $rsm->addFieldResult('a', 'project_id', 'id');

         $sql = 'select u.name, u.id, u.description
            from project u
            inner join task a on a.project_id=u.id
            where a.status=?
            group by(u.name)
            having count(*)>=8
            order by u.name';

         $query =  $em->createNativeQuery($sql, $rsm);
         $query->setParameter(1, 'completed');

         return $query->getResult();
     }

    public function getWithTasks()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM tshuvalovaPerformanceBundle:Project c LEFT JOIN c.tasks j'
        );

        return $query->getResult();
    }

}
