<?php

namespace tshuvalova\PerformanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getActiveTasks($project_id = null, $max = null, $offset = null )
    {
        $qb = $this->createQueryBuilder('j');

        if($project_id)
        {
            $qb->andWhere('j.project = :project_id')
                ->setParameter('project_id', $project_id);
        }


        if($offset)
        {
            $qb->setFirstResult($offset);
        }

        $qb->addOrderBy('j.name');

        if($max)
        {
            $qb->setMaxResults($max);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function getCountActiveTasks($p_id)
    {
        $qb = $this->createQueryBuilder('j');
        $qb->select('count(j.id)');
        $qb->andWhere('j.project = :p_id')
            ->setParameter('p_id', $p_id);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }
}
