parameters:
#    tshuvalova_performance.example.class: tshuvalova\PerformanceBundle\Example

services:
#    tshuvalova_performance.example:
#        class: %tshuvalova_performance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
